### ISSUE TITLE
stuck at mssql_1

### ISSUE THREAD

**Issue by gbzret4d** [TheUltimateC0der/Deemixrr#10]
Im trying to install Deemixrr with the compose.yml but during the installing its getting stuck at the line:
mssql_1
Its running now for 1 hour and still no progress.

This is the log:

> deemixrr_1  | [cont-init.d] 10-adduser: exited 0.
> deemixrr_1  | [cont-init.d] 30-install-deemix: executing...
> deemixrr_1  | [cont-init.d] Installing Deemix ...
> mssql_1     | 2020-10-17 22:14:45.45 Server      Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64)
> mssql_1 Nov 30 2018 12:57:58
> mssql_1 Copyright (C) 2017 Microsoft Corporation
> mssql_1 Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)
> 2020-10-17 22:14:45.46 Server      UTC adjustment: 0:00
> 2020-10-17 22:14:45.46 Server      (c) Microsoft Corporation.
> 2020-10-17 22:14:45.46 Server      All rights reserved.
> 2020-10-17 22:14:45.46 Server      Server process ID is 4124.
> 2020-10-17 22:14:45.47 Server      Logging SQL Server messages in file '/var/opt/mssql/log/errorlog'.
> 2020-10-17 22:14:45.47 Server      Registry startup parameters:
> mssql_1  -d /var/opt/mssql/data/master.mdf
> mssql_1  -l /var/opt/mssql/data/mastlog.ldf
> mssql_1  -e /var/opt/mssql/log/errorlog
> 2020-10-17 22:14:45.47 Server      SQL Server detected 1 sockets with 4 cores per socket and 8 logical processors per socket, 8 total logical processors; using 8 logical processors based on SQL Server licensing. This is an informational message; no user action is required.
> 2020-10-17 22:14:45.49 Server      SQL Server is starting at normal priority base (=7). This is an informational message only. No user action is required.
> 2020-10-17 22:14:45.49 Server      Detected 51366 MB of RAM. This is an informational message; no user action is required.
> 2020-10-17 22:14:45.50 Server      Using conventional memory in the memory manager.
> 2020-10-17 22:14:45.51 Server      Large Page Allocated: 32MB
> 2020-10-17 22:14:45.90 Server      Buffer pool extension is already disabled. No action is necessary.
> 2020-10-17 22:14:46.11 Server      InitializeExternalUserGroupSid failed. Implied authentication will be disabled.
> 2020-10-17 22:14:46.11 Server      Implied authentication manager initialization failed. Implied authentication will be disabled.
> 2020-10-17 22:14:46.11 Server      Successfully initialized the TLS configuration. Allowed TLS protocol versions are ['1.0 1.1 1.2']. Allowed TLS ciphers are ['ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!DHE-RSA-AES256-GCM-SHA384:!DHE-RSA-AES128-GCM-SHA256:!DHE-RSA-AES256-SHA:!DHE-RSA-AES128-SHA'].
> deemixrr_1  | [cont-init.d] Installing Deemix: Done!
> deemixrr_1  | [cont-init.d] 30-install-deemix: exited 0.
> deemixrr_1  | [cont-init.d] 40-permissions: executing...
> deemixrr_1  | [cont-init.d] Setting permissions on /app ...
> deemixrr_1  | [cont-init.d] Setting permissions on /app Done!
> deemixrr_1  | [cont-init.d] 40-permissions: exited 0.
> 2020-10-17 22:14:46.16 Server      The maximum number of dedicated administrator connections for this instance is '1'
> 2020-10-17 22:14:46.16 Server      Node configuration: node 0: CPU mask: 0x00000000000000ff:0 Active CPU mask: 0x00000000000000ff:0. This message provides a description of the NUMA configuration for this computer. This is an informational message only. No user action is required.
> deemixrr_1  | [cont-init.d] 99-custom-scripts: executing...
> deemixrr_1  | [custom-init] no custom files found exiting...
> deemixrr_1  | [cont-init.d] 99-custom-scripts: exited 0.
> deemixrr_1  | [cont-init.d] done.
> deemixrr_1  | [services.d] starting services
> deemixrr_1  | [services.d] done.
> 2020-10-17 22:14:46.28 Server      Using dynamic lock allocation.  Initial allocation of 2500 Lock blocks and 5000 Lock Owner blocks per node.  This is an informational message only.  No user action is required.
> 2020-10-17 22:14:46.28 Server      In-Memory OLTP initialized on standard machine.
> 2020-10-17 22:14:46.38 Server      Database Instant File Initialization: enabled. For security and performance considerations see the topic 'Database Instant File Initialization' in SQL Server Books Online. This is an informational message only. No user action is required.
> ForceFlush is enabled for this instance.
> 2020-10-17 22:14:46.40 Server      Query Store settings initialized with enabled = 1,
> 2020-10-17 22:14:46.41 spid6s      Starting up database 'master'.
> 2020-10-17 22:14:46.41 Server      Software Usage Metrics is disabled.
> deemixrr_1  | info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
> deemixrr_1  |       User profile is available. Using '/config/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
> ForceFlush feature is enabled for log durability.
> 2020-10-17 22:14:46.94 spid6s      Resource governor reconfiguration succeeded.
> 2020-10-17 22:14:46.94 spid6s      SQL Server Audit is starting the audits. This is an informational message. No user action is required.
> 2020-10-17 22:14:46.96 spid6s      SQL Server Audit has started the audits. This is an informational message. No user action is required.
> 2020-10-17 22:14:47.10 spid6s      SQL Trace ID 1 was started by login "sa".
> 2020-10-17 22:14:47.14 spid6s      Server name is '7003c72e517d'. This is an informational message only. No user action is required.
> 2020-10-17 22:14:47.17 spid22s     Starting up database 'msdb'.
> 2020-10-17 22:14:47.17 spid23s     Starting up database 'Deemixrr'.
> 2020-10-17 22:14:47.17 spid8s      Starting up database 'mssqlsystemresource'.
> 2020-10-17 22:14:47.18 spid24s     Always On: The availability replica manager is starting. This is an informational message only. No user action is required.
> 2020-10-17 22:14:47.19 spid24s     Always On: The availability replica manager is waiting for the instance of SQL Server to allow client connections. This is an informational message only. No user action is required.
> 2020-10-17 22:14:47.19 spid8s      The resource database build version is 14.00.3048. This is an informational message only. No user action is required.
> 2020-10-17 22:14:47.26 spid8s      Starting up database 'model'.
> 2020-10-17 22:14:47.44 spid18s     A self-generated certificate was successfully loaded for encryption.
> 2020-10-17 22:14:47.46 spid18s     Server is listening on [ 'any' <ipv4> 1433].
> 2020-10-17 22:14:47.47 Server      Server is listening on [ 127.0.0.1 <ipv4> 1434].
> 2020-10-17 22:14:47.48 Server      Dedicated admin connection support was established for listening locally on port 1434.
> 2020-10-17 22:14:47.52 spid18s     SQL Server is now ready for client connections. This is an informational message; no user action is required.
> deemixrr_1  | info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
> deemixrr_1  |       Entity Framework Core 3.1.7 initialized 'AppDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
> 2020-10-17 22:14:47.82 spid23s     Parallel redo is started for database 'Deemixrr' with worker pool size [4].
> 2020-10-17 22:14:47.87 spid8s      Polybase feature disabled.
> 2020-10-17 22:14:47.88 spid8s      Clearing tempdb database.
> 2020-10-17 22:14:47.98 spid6s      Parallel redo is shutdown for database 'Deemixrr' with worker pool size [4].
> 2020-10-17 22:14:48.51 spid8s      Starting up database 'tempdb'.
> 2020-10-17 22:14:48.83 spid8s      The tempdb database has 1 data file(s).
> 2020-10-17 22:14:48.83 spid26s     The Service Broker endpoint is in disabled or stopped state.
> 2020-10-17 22:14:48.83 spid26s     The Database Mirroring endpoint is in disabled or stopped state.
> 2020-10-17 22:14:48.86 spid26s     Service Broker manager has started.
> 2020-10-17 22:14:48.88 spid6s      Recovery is complete. This is an informational message only. No user action is required.
> deemixrr_1  | info: Microsoft.EntityFrameworkCore.Database.Command[20101]
> deemixrr_1  |       Executed DbCommand (19ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> deemixrr_1  |       SELECT 1
> deemixrr_1  | info: Microsoft.EntityFrameworkCore.Database.Command[20101]
> deemixrr_1  |       Executed DbCommand (13ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> deemixrr_1  |       SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
> deemixrr_1  | info: Microsoft.EntityFrameworkCore.Database.Command[20101]
> deemixrr_1  |       Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> deemixrr_1  |       SELECT 1
> deemixrr_1  | info: Microsoft.EntityFrameworkCore.Database.Command[20101]
> deemixrr_1  |       Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> deemixrr_1  |       SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
> deemixrr_1  | info: Microsoft.EntityFrameworkCore.Database.Command[20101]
> deemixrr_1  |       Executed DbCommand (10ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> deemixrr_1  |       SELECT [MigrationId], [ProductVersion]
> deemixrr_1  |       FROM [__EFMigrationsHistory]
> deemixrr_1  |       ORDER BY [MigrationId];
> deemixrr_1  | info: Microsoft.EntityFrameworkCore.Migrations[20405]
> deemixrr_1  |       No migrations were applied. The database is already up to date.
> deemixrr_1  | info: Hangfire.SqlServer.SqlServerObjectsInstaller[0]
> deemixrr_1  |       Start installing Hangfire SQL objects...
> deemixrr_1  | info: Hangfire.SqlServer.SqlServerObjectsInstaller[0]
> deemixrr_1  |       Hangfire SQL objects installed.
> deemixrr_1  | info: Hangfire.BackgroundJobServer[0]
> deemixrr_1  |       Starting Hangfire Server using job storage: 'SQL Server: mssql@Deemixrr'
> deemixrr_1  | info: Hangfire.BackgroundJobServer[0]
> deemixrr_1  |       Using the following options for SQL Server job storage: Queue poll interval: 00:00:15.
> deemixrr_1  | info: Hangfire.BackgroundJobServer[0]
> deemixrr_1  |       Using the following options for Hangfire Server:
> deemixrr_1  |           Worker count: 2
> deemixrr_1  |           Listening queues: 'default'
> deemixrr_1  |           Shutdown timeout: 00:00:15
> deemixrr_1  |           Schedule polling interval: 00:00:15
> deemixrr_1  | info: Hangfire.Server.BackgroundServerProcess[0]
> deemixrr_1  |       Server dac2a696124a:3390:2587e730 successfully announced in 146.1286 ms
> deemixrr_1  | info: Hangfire.Server.BackgroundServerProcess[0]
> deemixrr_1  |       Server dac2a696124a:3390:2587e730 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler...
> deemixrr_1  | info: Hangfire.Server.BackgroundServerProcess[0]
> deemixrr_1  |       Server dac2a696124a:3390:2587e730 all the dispatchers started
> deemixrr_1  | info: Microsoft.Hosting.Lifetime[0]
> deemixrr_1  |       Now listening on: http://0.0.0.0:5000
> deemixrr_1  | info: Microsoft.Hosting.Lifetime[0]
> deemixrr_1  |       Application started. Press Ctrl+C to shut down.
> deemixrr_1  | info: Microsoft.Hosting.Lifetime[0]
> deemixrr_1  |       Hosting environment: Production
> deemixrr_1  | info: Microsoft.Hosting.Lifetime[0]
> deemixrr_1  |       Content root path: /app
> mssql_1     |

Any idea?
Thanks!

**Comment by gbzret4d** [comment]
Any ideas?

**Comment by lpnueg4** [comment]
Same issue

**Comment by TheUltimateC0der** [comment]
I do not understand what the issue is. Its seems that everything is working as expected.
