### ISSUE TITLE
Disable TLS by default

### ISSUE THREAD

**Issue by humor4fun** [TheUltimateC0der/Deemixrr#13]
The default configuration provided includes an SSL/TLS connection. This makes it nearly impossible to just stand up a container and access the site using the loopback address because of browser protections and the auto-forwarding that happens inside the container (http->https).

I suggest either building the default container to work without a TLS cert and not force the traffic upgrade on every response, or build in certbot to fetch a tls cert for the domain specified.

I've been trying to play with this on Windows 10 with the Docker desktop app.

**Comment by humor4fun** [comment]
Right after posting this I thought to look for closed issues and found this: https://github.com/TheUltimateC0der/Deemixrr/issues/5

I just tested the `nightly` build and found that solves this issue. I suggest you add a comment to the "Host your own" wiki page.

**Comment by TheUltimateC0der** [comment]
Thank your for reminding me that I havent merged `develop` into `master`

And thank you for contributing to the Wiki. I moved your stuff to an own Troubleshooting page!

Thanks a lot!
