### ISSUE TITLE
Export page shows variable name

### ISSUE THREAD

**Issue by humor4fun** [TheUltimateC0der/Deemixrr#26]
The export page for Artists shows the variable names and not the contents of the Artist lists.

https://github.com/TheUltimateC0der/Deemixrr/blob/develop/Deemixrr/Views/Artist/Export.cshtml#L26
https://github.com/TheUltimateC0der/Deemixrr/blob/develop/Deemixrr/Views/Artist/Export.cshtml#L43
https://github.com/TheUltimateC0der/Deemixrr/blob/develop/Deemixrr/Views/Artist/Export.cshtml#L60

![image](https://user-images.githubusercontent.com/7505051/107528452-d8fabc80-6b87-11eb-8709-b113e58c5a33.png)

**Comment by TheUltimateC0der** [comment]
Fixed it by removing `asp-for="Artists"`
