### ISSUE TITLE
Size Calculation could be rounded

### ISSUE THREAD

**Issue by humor4fun** [TheUltimateC0der/Deemixrr#28]
![image](https://user-images.githubusercontent.com/7505051/107529247-adc49d00-6b88-11eb-8f46-d1f25b9f843a.png)

The updated size calculation for folders could be rounded to 2 or 3 decimal places so that this kind of thing doesn't happen. We don't really need that level of detail when the units are so large.

**Comment by TheUltimateC0der** [comment]
Done with #29
