### ISSUE TITLE
Database support

### ISSUE THREAD

**Issue by grahamPegNetwork** [TheUltimateC0der/Deemixrr#3]
I was about to start setting this up when I noticed that the example docker-compose.yml uses MSSQL as its storage engine. Coming from an open source background I would expect this to either use mysql/mariadb, or even sqlite. 

I will admit, I'm biased against MS based products, and would assume the motivation might be familiarity? If there is a performance or feature related argument I would be glad to be educated.

MySQL: Probably an industry standard for many open source projects, likely to already be running on a host machine
MariaDB: Same as above, somewhat better performance and other perks.
Sqlite: Lightweight, can save into main config directory, no dependencies on other images (most of my other services use something like this)
Postgres: Better performance I believe, I'm no expect on it but some admins prefer it
Flat files: Depends on what you are storing, if it is a config file with credentials and a list of artists maybe the DB isn't even a necessary tool?

Often with tools like this, you see the default storage engine sqlite/flat files, with the option for a more performant database for advanced users. 

I'm still considering using this tool as-is, but currently have two options:
1. Take the MSSQL requirement, knowing it will run but have reservations and an icky feeling in the back of my mind
2. Try to point it at an existing MySQL container, cross my fingers and hope it works.

**Comment by TheUltimateC0der** [comment]
Currently working on it.

Providers will be SQLite and MySQL/MariaDb

Downside: I do not put the effort in for a migration from the old mssql db to any of the new supported ones. But @humor4fun implemented a new export option, in order to be able to make a complete export of your artists and playlists for a easy migration by yourself.

**Comment by TheUltimateC0der** [comment]
We now have the option to use SQLite and MySQL/MariaDb

**Comment by grahamPegNetwork** [comment]
Thanks @TheUltimateC0der , just browsed across this. Looking forward to trying it out!
