### ISSUE TITLE
 Keeps Redirecting to HTTPS which does not work

### ISSUE THREAD

**Issue by NicolasNatale** [TheUltimateC0der/Deemixrr#5]
Hello,

I followed the Linux instructions and after setting up, every time a page loads it redirects to HTTPS. Whenever it does this, I receive this error.

![image](https://user-images.githubusercontent.com/20688836/93373570-852bb780-f823-11ea-9dc1-15a3a1e93a7c.png)

**Comment by ItsNoted** [comment]
I believe it's meant to be behind reverse proxy and a domain. Works fine when I put it behind reverse proxy. Otherwise I face the same issue you have.

**Comment by kkazakov** [comment]
How do you put it behind reverse proxy? I just did that (nginx), but it does not work, I keep getting errors. All my other containers are behind 80->443 redirect and proxy_pass and they work.

Edit: nevermind, removed bunch of nginx proxy parameters and left the basics and that worked.

**Comment by NicolasNatale** [comment]
> I believe it's meant to be behind reverse proxy and a domain. Works fine when I put it behind reverse proxy. Otherwise I face the same issue you have.

Are you using the Linux docker container? The instructions don't state a reverse proxy is needed, and in the docker compose file there are ports mapped, with instructions to remove mapped ports if using a reverse proxy.

**Comment by TheUltimateC0der** [comment]
> Are you using the Linux docker container? The instructions don't state a reverse proxy is needed, and in the docker compose file there are ports mapped, with instructions to remove mapped ports if using a reverse proxy.

My bad. Currently deemixrr only supports reverse proxy connections and no direct calls to the port that has been mapped. The reverse proxy must serve HTTPS, as this will lead to more security. I will have a look at how I can change it, so that both non-reverseproxy and reverseproxy setups work.

**Comment by kkazakov** [comment]
> My bad. Currently deemixrr only supports reverse proxy connections and no direct calls to the port that has been mapped. The reverse proxy must serve HTTPS, as this will lead to more security. I will have a look at how I can change it, so that both non-reverseproxy and reverseproxy setups work.

If you can redirect to relative paths instead of absolute, then the reverse proxy will still work, but also the unprotected one will.

**Comment by NicolasNatale** [comment]
> > My bad. Currently deemixrr only supports reverse proxy connections and no direct calls to the port that has been mapped. The reverse proxy must serve HTTPS, as this will lead to more security. I will have a look at how I can change it, so that both non-reverseproxy and reverseproxy setups work.
> 
> If you can redirect to relative paths instead of absolute, then the reverse proxy will still work, but also the unprotected one will.

I ended up setting up a reverse proxy (Traefik) to utilize the application. It works perfectly fine, but at least it is now known you need a proxy unless this is changed.

**Comment by vmoucadeau** [comment]
Hello, I have the same bug, how can I use Deemixrr with a reverse proxy?

**Comment by jterpstra1** [comment]
> > > My bad. Currently deemixrr only supports reverse proxy connections and no direct calls to the port that has been mapped. The reverse proxy must serve HTTPS, as this will lead to more security. I will have a look at how I can change it, so that both non-reverseproxy and reverseproxy setups work.
> > 
> > 
> > If you can redirect to relative paths instead of absolute, then the reverse proxy will still work, but also the unprotected one will.
> 
> I ended up setting up a reverse proxy (Traefik) to utilize the application. It works perfectly fine, but at least it is now known you need a proxy unless this is changed.

I'm trying this aswel (using traefik) but I can't get it to work. Could you help me a bit?

**Comment by TheUltimateC0der** [comment]
I added a fix according to the documentation https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

@NicolasNatale @kkazakov @GENERATION2GEEK I would love to hear your feedback by using the `:nightly` tag of demixrr without reverse proxy. Please report back if it works.

**Comment by vmoucadeau** [comment]
Thanks, I will try again

**Comment by vmoucadeau** [comment]
I'm sorry, but I don't understand what I should do, where should I put ":nightly"?

**Comment by zimmra** [comment]
> I'm sorry, but I don't understand what I should do, where should I put ":nightly"?

when calling for the container from dockerhub instead of theultimatecoder/deemixrr:latest you would use theultimatecoder/deemixrr:nightly

**Comment by zimmra** [comment]
> I added a fix according to the documentation https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1
> 
> @NicolasNatale @kkazakov @GENERATION2GEEK I would love to hear your feedback by using the `:nightly` tag of listrr without reverse proxy. Please report back if it works.

This worked for me, it's not forcing me to https:// anymore

Fyi you referenced listrr, think you're working on too many things at once ;)

**Comment by TheUltimateC0der** [comment]
@zimmra thx for the hint. I edited it.

@GENERATION2GEEK How exactly are you trying to deploy it? Please show your `docker-compose.yaml` or your docker command. Be sure to replace passwords and domain names before posting.

**Comment by vmoucadeau** [comment]
Thank you @zimmra and @TheUltimateC0der for your answers.
That's exactly what I did, I replaced "latest" by "nightly" in docker-compose-.yaml, except... the file hadn't saved...
I have just tested and it works with http, without domain name. Sorry for the inconvenience.
