### ISSUE TITLE
settings link does nothing from the menu

### ISSUE THREAD

**Issue by appiekap653** [TheUltimateC0der/Deemixrr#9]
all the href for the dropdown menu items profile, settings and activities are set to '#'
no pages are loading making the menu items useless

**Comment by TheUltimateC0der** [comment]
Thats correct and "intended".

**Comment by appiekap653** [comment]
> Thats correct and "intended".

An "intended" menu with different user interface items that don't work?

Never heared of that one before, can you explain?

**Comment by TheUltimateC0der** [comment]
You heard it here first!

Actually there were plans to utilize these links, but I havent found a use for it. So they are still there, cause I am a lazy fuck.

If they are annoying to you, make a PR :P
